# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Test Automation
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a test script
        run: echo Run a test to make sure code compiles

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: Test Automation
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/my-app
            git pull origin main
            ./restart_service.sh
